### ISSUE TITLE
Have compiled...now what?

### ISSUE THREAD

**Issue by elementalcollision** [AllenDang/PngOptimizier#1]
Compiled via 
`cargo build --release --features=fltk/fltk-bundled`
and...now what?  

(MacOS, M1 Pro Max)

**Comment by AllenDang** [comment]
`cargo build --release` and `cargo bundle --release`, you will need to `cargo install cargo-bundle` to invoke cargo bundle.
And then you could find the app bundle at `.../release/bundle/...`

**Comment by elementalcollision** [comment]
thanks, that solved it.  Still needed to run the fltk-bundled flag on my system but that fixed it.

Should add this to release notes, esp. for less experience rustaceans.
