### ISSUE TITLE
add options for some of the oxipng command line switches to not change bit depth, color type, etc?

### ISSUE THREAD

**Issue by hchorey** [AllenDang/PngOptimizier#2]
Hey Allen,

Just tried PngOptimizier today, and it's pretty great!  Would it be possible for you to add some settings / options to the app that would allow you to select some of the other command line switches that oxipng has?  The following ones especially I would find useful:

      --nb
          Do not change bit depth

      --nc
          Do not change color type

      --np
          Do not change color palette

      --ng
          Do not change to or from grayscale

      --nx
          Do not perform any transformations and do not deinterlace by default.

I hope something along those lines would be feasible.  :)

**Comment by AllenDang** [comment]
@hchorey It's done, check the newest master.
